### ISSUE TITLE
how to connect UniTIme server to another server database mysql??

### ISSUE THREAD

**Issue by Abdulaziz-KTA** [UniTime/unitime#102]
how to connect UniTIme server to another server database mysql??
I want to connect the database to another server for data security and controlled by the database team

**Comment by tomas-muller** [comment]
See the Customization section of the [UniTime Installation](https://help.unitime.org/installation#h.cn0eyym49zu1) document.

The database connection can be changed using custom properties. However, please note that these properties cannot be defined using the UniTime application (Administration / Defaults / Configuration menu item) since the database connection needs to be configured before the database can be accessed. For instance, custom.properties file can contain:
```
# MySQL Configuration Example
connection.url=jdbc:mysql://localhost:3306/timetable?serverTimezone=Europe/Prague
connection.username=timetable
connection.password=unitime
connection.driver_class=com.mysql.jdbc.Driver
dialect=org.hibernate.dialect.MySQLInnoDBDialect
tmtbl.uniqueid.generator=org.hibernate.id.TableHiLoGenerator
default_schema=timetable
```

**Comment by Abdulaziz-KTA** [comment]
I do that not work 
inside this "C:\Program Files\Apache Software Foundation\Tomcat 8.5\webapps\UniTime.war\WEB-INF\lib\timetable.jar\application.properties" this is correct??

**Comment by tomas-muller** [comment]
No, that is not correct. Please read the documentation. You can create a custom properties file outside of the UniTime.war file, for example ```C:\Program Files\Apache Software Foundation\Tomcat 8.5\conf\unitime.properties``` and put all these properties in there. For this file to be loaded by UniTime, you need to add the following line in the ```C:\Program Files\Apache Software Foundation\Tomcat 8.5\conf\catalina.properties```:
```
tmtbl.custom.properties=C:\\Program Files\\Apache Software Foundation\\Tomcat 8.5\\conf\\unitime.properties
```

This is also mentioned in the [UniTime Windows installation](https://docs.google.com/document/d/1VCscHsSpazzmsh_DQZiicqOjAda3eX0f4S9oxlll8CY/edit#) document, section 5c.

**Comment by Abdulaziz-KTA** [comment]
thank you now is work.
