### ISSUE TITLE
this is bug in Event Room Availability???

### ISSUE THREAD

**Issue by Abdulaziz-KTA** [UniTime/unitime#103]
when I search department  for one day the result is good.
![image](https://user-images.githubusercontent.com/46826627/147551731-9b637da4-a8e2-4965-924f-0c9adb90a38c.png)

more filtering about room for one day I get nothing.
![image](https://user-images.githubusercontent.com/46826627/147551883-2a8bb4a0-ace6-42e9-a16e-efc980358ede.png)

but when I set 5 days the result is good.
![image](https://user-images.githubusercontent.com/46826627/147552274-ccdaf46b-a9e1-4210-8426-71c94a41ad7f.png)

**Comment by tomas-muller** [comment]
I am not able to reproduce this problem. Is there any error in the Tomcat's log or in the JavaScript console of your browser? Could you please retry with the latest release of UniTime 4.5?

**Comment by Abdulaziz-KTA** [comment]
![image](https://user-images.githubusercontent.com/46826627/147907178-333dd855-a00b-4f68-907d-dff05df8e94d.png)
UniTime 4.6.1 not work

**Comment by tomas-muller** [comment]
I am still not able to reproduce your problem. **Is there any error in the Tomcat's log or in the JavaScript console of your browser?** The page does not usually show the Print and Sort by buttons without showing a table in between -- if the Locations filter does not match any room, there is an error message. Otherwise, the table gets displayed even when there are no events on the selected date.

Please note that UniTime 4.6.1 (dev) is not an official build (those are available at [builds.unitime.org](https://builds.unitime.org/)).

Does the page work when another single day (other than September 5) is selected? Have you changed the ```unitime.events.gridStartDay``` property on the Application Configuration page? If so, does the page works for you when it is set back to 0?

**Comment by Abdulaziz-KTA** [comment]
no error in log or JavaScript 
not work when set nitime.events.gridStartDay to 6 of one day if choice tow day is work

**Comment by Abdulaziz-KTA** [comment]
is work when set `nitime.events.gridStartDay` 0  when choice one days.

**Comment by tomas-muller** [comment]
This has been corrected (commit 0a95a43) in UniTime 4.6.63 or later.
