### ISSUE TITLE
I'm getting this warning  WARN: Student 1397 not enrolled in any class of subpart. How can I resolve it?

### ISSUE THREAD

**Issue by EricoMutonks** [UniTime/unitime#118]

**Comment by tomas-muller** [comment]
This warning is caused by some earlier issue where no classes of a particular scheduling subpart are loaded in, e.g., because they have no available placements. A student requesting a course must attend one class of each scheduling subpart from one of the course configurations. You should see one of the following warnings in the log:

**Comment by EricoMutonks** [comment]
Thanks once again
