### ISSUE TITLE
Change the start working day of the week

### ISSUE THREAD

**Issue by hamdiRuwiss** [UniTime/unitime#131]
Greetings, is it possible to change the start week for unitime, so that it starts from Saturday instead of Monday.

**Comment by tomas-muller** [comment]
Yes, it is possible to change the first day of a week in UniTime.

There are a few configuration parameters (that can be set on the Administration > Defaults > Configuration page, or in the custom properties) that change the display so that a week starts on Sunday:

```
# Time Patterns: first day of week (0 is Monday, 1 is Tuesday, etc.)
unitime.timePattern.firstDayOfWeek=6

# Event Time Grid: first day of the week (0 is Monday, 1 is Tuesday, etc.)
unitime.events.gridStartDay=6

# Time Grid: first day of week (0 is Monday, 1 is Tuesday, etc.)
unitime.timeGrid.startDay=6

# Time Grid: defines an additional days of week (starting with 1, format is bitmap|name)
unitime.timeGrid.days14=1111001|Sunday - Thursday
```

And in the solver configuration (the following two parameters need to be created in the General Settings section on the Administration > Solver > Parameters page and set as follows)

```
1) First Day of a Week
  Name: General.FirstWorkDay
  Description: First Day of Week (0..Monday, 1..Tuesday,...)
  Type: integer
  Default: 6

2) Last Work Day of a Week
  Name: General.LastWorkDay
  Description: Last Work Day of Week (0..Monday, 1..Tuesday,...)
  Type: integer
  Default: 4
```
