### ISSUE TITLE
Error during "Run SQL Script"

### ISSUE THREAD

**Issue by plainplow** [UniTime/unitime#15]
I installed JDK, MySQL, and Apache Tomcat. And now when I get to the part where I run schema.sql in MySQL 5.5 I get an error that says: 

**Error During "Run SQL Script"

error calling Python module function
SQLIDEUtils.runSQLScript**

**Comment by tomas-muller** [comment]
Are there any more details on which line of the script failed? It could be the drop user command at the beginning of the script (the script is written to allow to recreate everything when executed for the second time; hence the -f parameter in the installation instructions).
```
mysql -uroot -p -f <schema.sql
mysql -uroot -p <woebegon-data.sql
```
If so, you could try to remove (or comment out) the [drop user line](https://github.com/UniTime/unitime/blob/master/Documentation/Database/MySQL/schema.sql#L23) and rerun the script.

**Comment by plainplow** [comment]
That one error screen is all that I get when I try to run schema.sql in Workbench. I tried commenting out that line you reference and it doesn't change anything.

Now, I am running this from my Windows 10 laptop, so I'm not sure if that platform isn't supported. But I have installed everything I'm supposed to. For some background, I'm trying this out personally before I bring it to my IT department.

**Comment by tomas-muller** [comment]
In the MySQLWorkbench, instead of File > Run SQL Script, could you try to use File > Open SQL Script followed by Query > Execute (All or Selection)? This way, you should see an output from each query of the [schema.sql](https://github.com/UniTime/unitime/blob/master/Documentation/Database/MySQL/schema.sql)  script.

You could also try to use the mysql command (from a command line) instead. Or, splitting the [schema.sql](https://github.com/UniTime/unitime/blob/master/Documentation/Database/MySQL/schema.sql) into smaller chunks to isolate the problem.

UniTime should work on any machine capable of running Java, Tomcat, and MySQL, including Windows 10. For production, a Linux-based system is recommended.

**Comment by plainplow** [comment]
Thank you for your patient help with this.

When I run the line that says `use mysql;` it gives this error:

Error during "Vertical Output"

error calling Pyhton module function
SQLIDEUtils.verticalOutput

**Comment by tomas-muller** [comment]
That is odd, the ```use mysql``` command only changes which database is going to be used by the following commands. The _mysql_ database is where the users and their roles reside.

I am not very familiar with the MySQLWorkbench. I have tried to reproduce the issue using MySQLWorkbench 6.3 connecting to a local instance of MySQL 5.6.12 on my Mac. I did not have any problems with either using  File > Run SQL Script or with File > Open SQL Script followed by Query > Execute (All or Selection).

You can try to create the timetable user and the timetable database manually, using the workbench and only use the [schema.sql](https://github.com/UniTime/unitime/blob/master/Documentation/Database/MySQL/schema.sql#L40) to create all the tables.

Or you can try to use the mysql command from a command line as indicated in the UniTime installation manual (using the [The MySQL Command-Line Tool](http://dev.mysql.com/doc/refman/5.5/en/mysql.html)).
