### ISSUE TITLE
Save failed: No row with the given identifier exists: [org.unitime.timetable.model.PosMajor#3407877]

### ISSUE THREAD

**Issue by plainplow** [UniTime/unitime#17]
I've been adding curricula all day. I was just about to go home, when I tried to save the last major I was working on and I get the following error.

Save failed: No row with the given identifier exists: [org.unitime.timetable.model.PosMajor#3407877]

It's as if the major or the academic area has been blown away. I have no idea what would have caused this.

**Comment by plainplow** [comment]
So, this is happening for the curriculum of a major in the Business academic area. 

I went into another Business major and just clicked Save. When I do, it says "**Validation failed, see errors below**" on the top of the Curriculum Details page and then lower on the page, under the Academic Area dropdown box it says "**Selected academic area has no majors without a curriculum.**"

When I back out of that screen, the curriculum is still there. I just apparently can't make any changes to any Business curricula.

Did somehow my "BU" academic area become corrupted? How would I fix that?

**Comment by plainplow** [comment]
Sorry, one more comment on this.

Before this error appeared I saw that I had two majors with identical IDs but different names. They were both in the Business academic area. So I went ahead and deleted one of them. After that is when these issues started.

I was surprised the program would let me make two different majors with the same ID in the first place. But I had deleted duplicates like this before without this problem happening. So, I'm not sure what makes this time different.

**Comment by plainplow** [comment]
Update on this. 

I created a new academic area (BS for Business instead of BU). 

I created the major that I deleted yesterday and assigned it the BS academic area. I reassigned all business majors to the new BS academic area. 

I then created a new curriculum for this new major and it worked. I reassigned all the business curricula to this new BS academic area and it all works fine.

Maybe that's all that needs to be done. I guess I would say it might be a good idea to make it so that you either can't create majors with a duplicate ID or that you can't delete them once they're created. I would think the former would be the better option.

**Comment by tomas-muller** [comment]
The exception "No row with the given identifier exists" suggests that Hibernate thinks there is an object that is no longer in the database (the object is in the Hibernate's second level cache). This usually happens when a database is changed outside of UniTime, but can also happen in some cases when an object is deleted but not all the relations are updated in the Hibernate cache. Using Administration > Utilities > Clear Cache should clear the Hibernate second level cache and allow you to continue working.

What do you mean by having two majors with the same ID? There are two IDs on majors:
  1. there is the unique id which should be unique and is a primary key in the appropriate table (pos_major.uniqueid); this MUST be unique and if you were able to create a second major with the same id, there is something wrong with your database (probably the value in the hibernate_unique_key table; have you been making changes to the UniTime database outside of UniTime?)
  2. the external unique id (pos_major.external_uid) which may not necessarily be unique (UniTime does not really care about the uniqueness of this field, it is only used for interaction with external systems); this external id is not editable in UniTime so the only way to get two records with the same external id is through the XML imports (or direct database manipulation)

**Comment by tomas-muller** [comment]
Ok, I am able to reproduce the "No row with the given identifier exists" error when I delete a major that is already used in a curriculum when the curriculum is in the Hibernate L2 cache. That is, when I delete the major shortly after looking at a curriculum for that major, the curriculum in question still thinks it is associated with the major that is no longer in the database (causing the no row issue when I try to revisit the said curriculum).

I think it should not be allowed to delete a major that is already being used in a curriculum (I have never expected that one would do this anyway and it can leave the curriculum in an inconsistent state -- not being related to any major, causing the validation errors). I will add this check into UniTime.

**Comment by plainplow** [comment]
Leave it to me to find something that no one would ever expect! :)

Thanks for all you do with this program, sir. It's been fun so far.
