### ISSUE TITLE
Examination scheduling

### ISSUE THREAD

**Issue by Animeakihabara** [UniTime/unitime#173]
When i solve using basic parameter, i got the result that some very first day in the available time for examinations have a lot of exams while the last few days in the available time literally don't have any exam, and more over some constraints like direct conflict or more than 2 A day conflicts have a big number, the easier way I can see that I can move some examination into the last few day which don't have much exam even no exam, so how can i do that with out do it manual by myself, is there any way to setup constraint to solve this problems?

**Comment by Animeakihabara** [comment]
for more specified, i have 14 days for examinations, the examination timetable i got for first 4 days is 931 over 1140 exam i already have(over 80% exam)
![2024-06-13 10 41 01](https://github.com/UniTime/unitime/assets/37822581/d4d223a5-592a-4fc9-8af8-9857cc207447)
![2024-06-13 10 41 03](https://github.com/UniTime/unitime/assets/37822581/bb2e3f23-e3ef-46a8-980d-4084485d7590)
![2024-06-13 10 40 53](https://github.com/UniTime/unitime/assets/37822581/f6b9b640-97cc-4fa5-8533-50ee9c280c0c)
![2024-06-13 10 40 56](https://github.com/UniTime/unitime/assets/37822581/817b0bb0-871a-4375-9524-d89b10bdc9b7)
![2024-06-13 10 40 58](https://github.com/UniTime/unitime/assets/37822581/2513ec32-0a17-43da-9231-831d0a063f81)

**Comment by tomas-muller** [comment]
Quick question: Is the solver able to assign all exams? That is, on the Examination Timetabling Solver page, it shows 100% assigned variables? Most of the optimization happens only after the solver is able to place all exams.

If the solver is able to assign all exams, could you please share your data with me (using the Export XML button on the Examination Timetabling Solver page)?

If the solver is NOT able to assign all exams, you need to check the Not-assigned Exams (and/or the Conflicts Statistics) pages and fix the inconsistencies in the problem.

**Comment by Animeakihabara** [comment]
All exam have been assigned this is the result in XML(I cannot upload XML, so I zipped it)
[exam-solution (3).xml.zip](https://github.com/user-attachments/files/15827408/exam-solution.3.xml.zip)

**Comment by tomas-muller** [comment]
Your problem is shaped by the Same Period distribution preferences. They are all required, and 1151 of your 1154 exams are present in at least one required Same Period preference. Besides generating a lot of direct conflicts that cannot be avoided, they also make it extremely hard for the solver to make local changes as each exam is, on average, required to be at the same period as 7 - 8 other exams. When I make all the Same Period preferences soft (preferred instead of required), the solver can quickly come up with a solution that has no student conflicts (no directs, no more than two exams on a day, no back-to-backs). But some of the Same Period preferences will remain not satisfied.

Also, by default, the solver tries to put each exam as early as possible in the examination week (it will pick the earliest possible period from those that are otherwise equal, e.g., have the same student conflicts). This can be avoided by setting the following two solver configuration parameters to zero:
Exam rotation weight (defaults to 0.001)
Examination period index weight (defaults to 0.0000001)

**Comment by tomas-muller** [comment]
Closing the issue as no additional questions were provided.

**Comment by tomas-muller** [comment]
FYI: In the most recent UniTime release ([4.8.159](https://github.com/UniTime/unitime/releases/tag/v4.8.159)), handling of soft distribution preferences has been significantly improved. Previously, a distribution was considered violated if any of the two exams in the constraint were in violation. In the new implementation, the penalization is based on how many examination pairs are violated. This helps the solver gradually decrease the number of violations during the search.

So, looking at your problem back from June, if all the Same Period distributions are made preferred instead of required, the solver is able to ensure that over 96% of examination pairs that are preferred to be in the same period are placed in the same period.
