### ISSUE TITLE
Timetable Grid returns nothing

### ISSUE THREAD

**Issue by Mertcikla** [UniTime/unitime#43]
Timetable Grid returns nothing. The issue occurs only when Resource is selected as Curriculum even without any filtering. The page functionality works fine for other types. I have curricula already defined in UniTime. When committed I can access the curriculum schedules from the Events->Timetable page as intended.

**Comment by tomas-muller** [comment]
This is likely because there are no curricula defined or loaded into the solver.

Do you have any curricula defined? Are you loading the data into the solver using Curriculum Course Demands or Curriculum Last Like Course Demands selected in the Student course demands parameter?

It is possible to show curricula even when other sources of student course demands are used, but in this case, the last-like or real student must have their academic areas, majors, and classifications filled in.

**Comment by Mertcikla** [comment]
Thanks for the quick response. The issue was we were not loading the solver using Curricula course demands as you described.
