### ISSUE TITLE
UniTime 4.4.130 failed to start up properly, please check the application log for more details.

### ISSUE THREAD

**Issue by tulakov77** [UniTime/unitime#53]
![image](https://user-images.githubusercontent.com/57991959/69477890-88296780-0e0d-11ea-8734-f34ce657b8df.png)

**Comment by tomas-muller** [comment]
The problem is that UniTime is not able to connect to the database:

`java.sql.SQLException: Access denied for user 'timetable'@'localhost' (using password: YES)`

Was the user timetable created? Was there any error/message printed during the creation of the timetable database (execution of file schema.sql)? Are you using the default password (unitime)?

You can verify some of that by checking the content of table mysql.user (there should be a line with user=timetable). You can also try to connect to the database as timetable user using mysql tool with the following options (also trying to use the same port and protocol as the UniTime application):

`mysql --user=timetable --password=unitime --port=3306 --host=localhost --protocol=TCP timetable`

If you are able to connect to mysql with `mysql -utimetable -punitime timetable` but not with `mysql --user=timetable --password=unitime --port=3306 --host=localhost --protocol=TCP timetable`, the problem could be that [TCP/IP networking is disabled.](https://dev.mysql.com/doc/refman/5.5/en/mysql-config-wizard-networking.html)
