### ISSUE TITLE
Right To Left

### ISSUE THREAD

**Issue by Moh3Azzam** [UniTime/unitime#67]
in my localhost I changed unitime.locale to ar and the pages not go from right to left and also tried localhost/login.jsp?locale=ar i got the same result
![image](https://user-images.githubusercontent.com/37277171/89779145-0ac69400-db0f-11ea-8bf2-72e59405eacd.png)
![image](https://user-images.githubusercontent.com/37277171/89779162-11eda200-db0f-11ea-9857-7d1d817346d9.png)

**Comment by tomas-muller** [comment]
The right-to-left support is only available in UniTime 4.5.

**Comment by Moh3Azzam** [comment]
i can't find 4.5 version 
![image](https://user-images.githubusercontent.com/37277171/89782359-6c89fc80-db15-11ea-9b42-558faf8919fd.png)

**Comment by tomas-muller** [comment]
https://builds.unitime.org

**Comment by Moh3Azzam** [comment]
i got this error
![image](https://user-images.githubusercontent.com/37277171/89783787-d2778380-db17-11ea-8d48-b498fe039a3c.png)

**Comment by tomas-muller** [comment]
Your UniTime instance does not seem to be correctly upgraded to version 4.5 (the page still says version 4.4.140 -- see the bottom left corner).

To upgrade an existing UniTime installation to 4.5, only the new [UniTime.war](https://builds.unitime.org/UniTime4.5/UniTime.war) file should be placed in the Tomcat/webapps folder instead of the existing one. All the necessary changes to the database are done automatically during the first deployment. The safest way to do so is as follows:
1. Stop tomcat
2. Backup the existing database
3. In Tomcat/webapps, remove UniTime folder and replace the existing UniTime.war with the new one
4. Delete the content of Tomcat/work folder.
5. Start the tomcat
