### ISSUE TITLE
Reservations student groups 

### ISSUE THREAD

**Issue by Abdulaziz-KTA** [UniTime/unitime#78]
what the best way to Reservations student groups ? and when I do it I get many group has 2 Course or more has same time and day

**Comment by tomas-muller** [comment]
In course timetabling, student group reservations are only used to restrict students to certain course configurations and/or classes. For this to work, the student group has to be associated with some students that also do request the course (e.g., using Student Course Requests as student course demands).

Alternatively, it is also possible to rely on student group reservations to provide student demand data. In this case, the student groups must have the Expected Students parameter filled in and the General.StudentGroupCourseDemands solver parameter must be created and set to true. You can do that on the Administration > Solver > Parameters page, using the Add Solver Parameter button with the following parameters:
<img width="995" alt="Screen Shot 2021-03-22 at 14 26 38" src="https://user-images.githubusercontent.com/10631634/111996872-bced2200-8b1a-11eb-9790-5786df61d03b.png">

**Comment by Abdulaziz-KTA** [comment]
It is work Thank you

**Comment by Abdulaziz-KTA** [comment]
How to solve a student who has a schedule conflict, taking a subject from a second group that contradicts the time of a subject from the first group.
(not use students solver)
like: 
he has 3 subject same group A01(Math, Network, Programing) and 1 from A02(English).
Sub: Math. Groups: A01. 
Sub: English. Groups: A02. 
and both have same time and day.

**Comment by tomas-muller** [comment]
If there are certain class combinations that should not overlap in time (e.g., because you have students across groups taking them), you can put Requited Same Students distribution between them.

Or you would have to combine student groups with other student course demands, that would include such students (e.g., based on pre-registration, or the last year's course enrollments).

**Comment by Abdulaziz-KTA** [comment]
I got this warning and the size class changed, I don't want to change the size class.
I created two a student group reservation in lec 1, I want the specified number of students to be equal for groups.
![image](https://user-images.githubusercontent.com/46826627/127278671-806ab86e-6ca9-44b7-9620-60b9c362b69d.png)

**Comment by tomas-muller** [comment]
The warning is printed when there are students put in the class over the class limit, usually because of the reservation or the config/class limits below the student demands. The 4>2 means that the class limit is 2, but there were 4 students put in.

I cannot provide more details without seeing the input data.

**Comment by Abdulaziz-KTA** [comment]
![image](https://user-images.githubusercontent.com/46826627/127298056-d3bd0681-c117-4980-b288-2334f49f9937.png)
![image](https://user-images.githubusercontent.com/46826627/127298087-e9ec5899-4e02-4f18-84e2-edd04265f6e9.png)

**Comment by tomas-muller** [comment]
You have three student groups restricted to go to Lec 1. What are the expected sizes of these groups? If there are 2 for each, that would be 6 students going to Lec 1 which has a limit of 2.

**Comment by Abdulaziz-KTA** [comment]
should be equal to 2 for all 3 groups!
