### ISSUE TITLE
StudentMinimizeScheduleHoles criterion

### ISSUE THREAD

**Issue by suna-yusuf** [UniTime/unitime#84]
I enabled StudentMinimizeScheduleHoles criterion by adding org.cpsolver.coursett.criteria.additional.StudentMinimizeScheduleHoles to General.AdditionalCriteria
then adding distribution preference same student to group of classes and run the solver
but still have long time between classes on the same days
And Student class distance field in solver page show question mark value
![studenClassDistanceField](https://user-images.githubusercontent.com/83161968/115988388-29e45380-a5c2-11eb-9c73-d8a4740233b4.png)

it seems not to work! 
how can i use StudentMinimizeScheduleHoles criterion with same student distribution preference?

**Comment by tomas-muller** [comment]
It appears you have no students in the problem. The StudentMinimizeScheduleHoles criterion needs some form of student course demands in order to work. These could be in a form of last-years student course enrollments, curricula, the actual pre-registrations, or a combination of these -- see the Student Course Demand parameter of the [Solver](http://help.unitime.org/Solver) for more details about these options.

If you use distribution preferences to indicate which classes cannot overlap in time, you can also use distribution preferences to further restrict these classes during the day. For instance, see the Max Hours A Day, Work Day, Max Holes, or Max Break distributions from the [Additional Distribution Constraints](http://help.unitime.org/Additional_Distribution_Constraints).

**Comment by suna-yusuf** [comment]
Can I use student group reservations instead of same student distribution preference to indicate which classes cannot overlap in time
and if I do, will StudentMinimizeScheduleHoles criterion be work ?

**Comment by suna-yusuf** [comment]
Thank you
