### ISSUE TITLE
Examination Timetable Grid Not Available

### ISSUE THREAD

**Issue by mndeto** [UniTime/unitime#9]
Hello,

Since the upgrade to version 4.0, the Examination timetable grid disappeared/broke. Please check on it.

Attached, please find a screen shot for the whole page.

![broken](https://cloud.githubusercontent.com/assets/14832213/12912985/1a26654e-cf2d-11e5-966f-ef3eafa4f3a7.png)

**Comment by tomas-muller** [comment]
Please provide us with more details about the issue.

Do you mean the Examinations > Examination Timetabling > Timetable Grid page? Can you see other examination pages? If no, do you have examination periods defined? Also, please check the permissions. Permission "Examination Timetable" is needed for this page.

**Comment by mndeto** [comment]
Exactly, Examinations > Examination Timetabling > Timetable Grid
The other pages are fine. This page displays as shown in the image above. The grid which used to show below the filter no longer appears. Permission "Examination Timetable" is also granted.

**Comment by tomas-muller** [comment]
I am not able to reproduce this issue. Is there any error in the Tomcat log or in the JavaScript console of the browser? How are your examination periods defined?

What version of UniTime are you using? The version string "4.1.2 (dev)" indicates a custom build of UniTime 4.1. If that is the case, you may need to make a new build with the most recent source codes. UniTime 4.1 is in development and there have been a lot of changes done to it since August 2015.

If you want to build UniTime 4.0 instead, you need to use maint_UniTime40 branch. UniTime 4.1 resides on the master.

**Comment by mndeto** [comment]
I have noticed that the bag has been fixed in the January 2016 commit.

Thank you so much for your support. Your system is awesome!
