### ISSUE TITLE
FATAL: No classes to load

### ISSUE THREAD

**Issue by GuoYuanxinKevin** [UniTime/unitime#94]
Hi Tomas, 

I tried to use the course timetabling solver but after I clicked Load, the following message occured:
![image](https://user-images.githubusercontent.com/57183709/129873331-aee1a3dd-4747-4ad3-bc8c-4e19df00a792.png)

If I ignore the message and click start, I see the error:
![image](https://user-images.githubusercontent.com/57183709/129873504-dd8ff255-f921-49d4-b603-682a6421036a.png)

What could be the possible reason and how can I resolve it? Many thanks!

**Comment by tomas-muller** [comment]
The "No classes to load." error message means that were no classes loaded into the solver. There can be a couple of reasons for that:

1) There are no classes associated with the department(s) for which the data are being loaded into the solver. Please check the relation between the solver group you are trying to load (page Administration > Solver > Solver Groups) and department(s) associated with your classes (displayed as the class manager, e.g., check Administration > Academic Sessions > Subject Areas).

2) There are classes associated with the department(s), but they were not loaded because there is no time/room assignment available. This happens, e.g., when you do not have a time pattern associated with the class or the class requires a room bigger than any room available. These cases are displayed as warnings in the solver log (and as problems listed on the Solver page) when you try to load the data into the solver.

Please see the [Administrative User Manual](https://docs.google.com/document/d/1iuj9NwrqkiVeJvKn1Sd41qqaVEJGwO79y1KZo1mtwuw), [Course Timetabling Data Entry Manual](https://docs.google.com/document/d/1rjS_6ebwegSTcN5Iw57qui5CHG8_6TWnk8MCwBwAt58), and [Course Timetabling Solver Manual](https://docs.google.com/document/d/1NZmKnmrjM2Tqg7dO18cWcMIe_GrtilQtKw6d1WGWBtY) for more details (all these manuals are also available from the menu, under Help > Manuals).
