### ISSUE TITLE
Error in installation: Cannot create bean name.

### ISSUE THREAD

**Issue by iamfrancisalbert** [UniTime/unitime#95]
I have followed the instruction in https://docs.google.com/document/d/1y3mKe1accr8qYPIbADqW40fd4HcAYNfAwJpduloGOQ0/edit#

I also have added the set time zone as per the instruction in 4.5 when using MySQL 8.0

I came up with this error:
16-Sep-2021 10:03:09.688 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.listenerStart Exception sending context initialized event to listener instance of class [org.springframework.web.context.ContextLoaderListener]
	org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name '/classes': Unsatisfied dependency expressed through field 'authenticationManager'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.security.authenticationManager': Cannot resolve reference to bean 'ldapAuthProvider' while setting constructor argument with key [1]; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'ldapAuthProvider' defined in ServletContext resource [/WEB-INF/securityContext.xml]: Cannot create inner bean 'org.springframework.security.ldap.authentication.BindAuthenticator#670c76c8' of type [org.springframework.security.ldap.authentication.BindAuthenticator] while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name

**Comment by tomas-muller** [comment]
The error complains about ldapAuthProvider bean not being created, there must have been an earlier error explaining why.

Please note that UniTime 4.5 is not fully compatible with Java 16 or later due to the [JEP 396: Strongly Encapsulate JDK Internals by Default](https://www.oracle.com/java/technologies/javase/16-relnotes.html#JDK-8256299). Please use Java 8 or Java 11, which do offer a long-time support (LTS). If you wish to use Java 16 or later, you need to either use UniTime 4.6 (that is still being developed, the latest build is available at [https://builds.unitime.org](https://builds.unitime.org)), or you need to set the following Java parameters:
```
--illegal-access=permit --add-exports=java.naming/com.sun.jndi.ldap=ALL-UNNAMED
```

**Comment by tomas-muller** [comment]
Closing the issue as no additional information was provided.
