### ISSUE TITLE
Support Microsoft SSO using Azure OAuth2 

### ISSUE THREAD

**Issue by trevclaridge** [UniTime/unitime#98]
I plan to work on this as my undergraduate senior capstone project (to be completed by June).

**Comment by tomas-muller** [comment]
I am closing the ticket due to inactivity.

See commit 30a59af for how to enable OAuth2 authentication (currently only available on [dev_oauth2](https://github.com/UniTime/unitime/tree/dev_oauth2) branch). Though [UniTimeOAuth2ClientRegistrationRepository](https://github.com/UniTime/unitime/blob/30a59af495640e905aac3b7d1da3ff07189d9f86/JavaSource/org/unitime/timetable/spring/oauth2/UniTimeOAuth2ClientRegistrationRepository.java) would need to be extended to support Azure as only providers supported by [CommonOAuth2Provider](https://docs.spring.io/spring-security/site/docs/current/api/org/springframework/security/config/oauth2/client/CommonOAuth2Provider.html) are currently listed.
